package: dmriprep
sections:
- name: Summary
  reportlets:
  - bids: {datatype: figures, desc: summary, suffix: T1w}
- name: Anatomical
  reportlets:
  - bids:
      datatype: figures
      desc: conform
      extension: [.html]
      suffix: T1w
  - bids: {datatype: figures, suffix: dseg}
    caption: This panel shows the template T1-weighted image (if several T1w images
      were found), with contours delineating the detected brain mask and brain tissue
      segmentations.
    subtitle: Brain mask and brain tissue segmentation of the T1w
  - bids: {datatype: figures, space: .*, suffix: T1w, regex_search: True}
    caption: Spatial normalization of the T1w image to the <code>{space}</code> template.
    description: Results of nonlinear alignment of the T1w reference one or more template
      space(s). Hover on the panels with the mouse pointer to transition between both
      spaces.
    static: false
    subtitle: Spatial normalization of the anatomical T1w reference
  - bids: {datatype: figures, desc: reconall, suffix: T1w}
    caption: Surfaces (white and pial) reconstructed with FreeSurfer (<code>recon-all</code>)
      overlaid on the participant's T1w template.
    subtitle: Surface reconstruction
- name: Fieldmaps
  ordering: session,run,fmapid
  reportlets:
  - bids: {datatype: figures, desc: mapped, suffix: fieldmap}
    caption: Inhomogeneities of the <em>B<sub>0</sub></em> field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. Some scanners produce a <em>B<sub>0</sub></em>
      mapping of the field, using Spiral Echo Imaging (SEI) or postprocessing a "phase-difference"
      acquisition. The plot below shows an anatomical "magnitude" reference and the corresponding
      fieldmap.
    description: Hover over the panels with the mouse pointer to also visualize the intensity of the
      field inhomogeneity in Hertz.
    static: false
    subtitle: "Susceptibility-derived Distortion Correction (SDC): field inhomogeneity estimation"
  - bids: {datatype: figures, desc: phasediff, suffix: fieldmap}
    caption: Inhomogeneities of the <em>B<sub>0</sub></em> field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. A Gradient-Recalled Echo (GRE) scheme for the 
      mapping of the <em>B<sub>0</sub></em> inhomogeneities by subtracting the phase maps obtained at
      two subsequent echoes. The plot below shows an anatomical "magnitude" reference and the corresponding
      fieldmap.
    description: Hover over the panels with the mouse pointer to also visualize the intensity of the
      field inhomogeneity in Hertz.
    static: false
    subtitle: "Susceptibility-derived Distortion Correction (SDC): field inhomogeneity estimation"
  - bids: {datatype: figures, desc: pepolar, suffix: fieldmap}
    caption: Inhomogeneities of the <em>B<sub>0</sub></em> field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. Utilizing two or more images with different
      phase-encoding polarities (PEPolar) or directions, it is possible to estimate the inhomogeneity
      of the field. The plot below shows a reference EPI (echo-planar imaging) volume generated
      using two or more EPI images with varying phase-encoding blips.
    description: Hover on the panels with the mouse pointer to also visualize the intensity of the
      inhomogeneity of the field in Hertz.
    static: false
    subtitle: "Susceptibility-derived Distortion Correction (SDC): field inhomogeneity estimation"
- name: Diffusion
  ordering: session,acquisition,run
  reportlets:
  - bids: {datatype: figures, desc: validation, suffix: dwi}
  - bids: {datatype: figures, desc: brain, suffix: mask}
    caption: Average <em>b=0</em> that serves for reference in early preprocessing steps.
    descriptions: The reference <em>b=0</em> is obtained as the voxel-wise median across
      all <em>b=0</em> found in the dataset, after accounting for signal drift.
      The red contour shows the brain mask calculated using this reference <em>b=0</em>.
    subtitle: Reference <em>b=0</em> and brain mask
  - bids: {datatype: figures, desc: sdc, suffix: dwi}
    caption: Susceptibility distortions correction (SDC).
    description: The reportlet shows a <em>b=0</em> reference <em>before</em> and <em>after</em> distortion correction.
    static: false
    subtitle: Unwarping of susceptibility distortions
  - bids: {datatype: figures, desc: eddy, suffix: dwi}
    caption: Head-motion and eddy current corrected diffusion data
    description: Eddy current-induced geometric distortions and head-motion
      realignment parameters were estimated with the joint modeling of
      <code>eddy_openmp</code>, included in FSL.
    static: false
    subtitle: Eddy corrected diffusion data
  - bids: {datatype: figures, desc: coreg, suffix: dwi}
    caption: Diffusion-weighted data and anatomical data (EPI-space and T1w-space)
      were aligned with <code>mri_coreg</code> (FreeSurfer).
      WARNING - <code>bbregister</code> refinement rejected.
    description: Note that nearest-neighbor interpolation is used in this reportlet
      in order to highlight potential slice Inhomogeneities and other artifacts, whereas
      the final images are resampled using cubic B-Spline interpolation.
    static: false
    subtitle: Alignment of diffusion anatomical MRI data (volume based)
  - bids: {datatype: figures, desc: bbregister, suffix: dwi}
    caption: Diffusion-weighted data and anatomical data (EPI-space and T1w-space)
      were aligned with <code>bbregister</code> (FreeSurfer).
    description: Note that nearest-neighbor interpolation is used in this reportlet
      in order to highlight potential slice Inhomogeneities and other artifacts, whereas
      the final images are resampled using cubic B-Spline interpolation.
    static: false
    subtitle: Alignment of diffusion and anatomical MRI data (surface driven)
- name: About
  reportlets:
  - bids: {datatype: figures, desc: about, suffix: T1w}
