package: dmriprep
sections:
- name: Summary
  reportlets:
  - bids: {datatype: figures, desc: summary, suffix: T1w}
- name: Anatomical
  reportlets:
  - bids:
      datatype: figures
      desc: conform
      extension: [.html]
      suffix: T1w
  - bids: {datatype: figures, suffix: dseg}
    caption: This panel shows the template T1-weighted image (if several T1w images
      were found), with contours delineating the detected brain mask and brain tissue
      segmentations.
    subtitle: Brain mask and brain tissue segmentation of the T1w
  - bids: {datatype: figures, space: .*, suffix: T1w, regex_search: True}
    caption: Spatial normalization of the T1w image to the <code>{space}</code> template.
    description: Results of nonlinear alignment of the T1w reference one or more template
      space(s). Hover on the panels with the mouse pointer to transition between both
      spaces.
    static: false
    subtitle: Spatial normalization of the anatomical T1w reference
  - bids: {datatype: figures, desc: reconall, suffix: T1w}
    caption: Surfaces (white and pial) reconstructed with FreeSurfer (<code>recon-all</code>)
      overlaid on the participant's T1w template.
    subtitle: Surface reconstruction
- name: Fieldmaps
  ordering: session,run
  reportlets:
  - bids: {datatype: figures, desc: pepolar, suffix: fieldmap}
    caption: Inhomogeneities of the *B0* field introduce (oftentimes severe) spatial distortions
      along the phase-encoding direction of the image. Utilizing two or more images with different
      phase-encoding polarities (PEPolar) or directions, it is possible to estimate the inhomogeneity
      of the field. The plot below shows a reference EPI (echo-planar imaging) volume generated
      using two or more EPI images with varying phase-encoding blips.
    description: Hover on the panels with the mouse pointer to also visualize the intensity of the
      inhomogeneity of the field in Hertz.
    static: false
    subtitle: "Susceptibility-derived Distortion Correction (SDC): field inhomogeneity estimation"
- name: Diffusion
  ordering: session,acquisition,run
  reportlets:
  - bids: {datatype: figures, desc: validation, suffix: dwi}
  - bids: {datatype: figures, desc: brain, suffix: mask}
    caption: Average b=0 that serves for reference in early preprocessing steps.
    descriptions: The reference b=0 is obtained as the voxel-wise median across
      all b=0 found in the dataset, after accounting for signal drift.
      The red contour shows the brain mask calculated using this reference b=0.
    subtitle: Reference b=0 and brain mask
- name: About
  reportlets:
  - bids: {datatype: figures, desc: about, suffix: T1w}
