name: dmriprep
channels:
   - conda-forge
dependencies:
   - python=3.6
   - boto3
   - dask
   - dipy=0.15
   - graphviz
   - ipython
   - pandas
   - tqdm
   - pip:
     - "--editable=git+https://github.com/akeshavan/nipype@87e53615867c9850c359002909c71825343b2e35#egg=nipype"
     - "--editable=git+https://git.fmrib.ox.ac.uk/matteob/eddy_qc_release@57bb11da6a634c4195593fbc439ba9f8998157b0#egg=eddy_qc"
     - bids
     - duecredit
